// 더미 매치 데이터
export const matchData = [
  {
    id: 1,
    userId: 'user-1',
    nickname: '까칠한까마귀',
    matchRate: 94,
    status: 'online' as const,
    tags: ['FPS 마스터', '새벽 플레이어', '협력 지향'],
  },
  {
    id: 2,
    userId: 'user-2',
    nickname: '기분좋은곰',
    matchRate: 94,
    status: 'online' as const,
    tags: ['FPS 마스터', '새벽 플레이어', '협력 지향'],
  },
  {
    id: 3,
    userId: 'user-3',
    nickname: '상쾌한고양이',
    matchRate: 94,
    status: 'online' as const,
    tags: ['FPS 마스터', '새벽 플레이어', '협력 지향'],
  },
  {
    id: 4,
    userId: 'user-4',
    nickname: '날뛰는기린',
    matchRate: 85,
    status: 'online' as const,
    tags: ['캐주얼 게임', '주말 플레이어', '소셜'],
  },
  {
    id: 5,
    userId: 'user-5',
    nickname: '신비로운팬더',
    matchRate: 94,
    status: 'online' as const,
    tags: ['FPS 마스터', '새벽 플레이어', '협력 지향'],
  },
  {
    id: 6,
    userId: 'user-6',
    nickname: '친절한사자',
    matchRate: 88,
    status: 'online' as const,
    tags: ['RPG 마니아', '저녁 플레이어', '전략적'],
  },
  {
    id: 7,
    userId: 'user-7',
    nickname: '날뛰는기린',
    matchRate: 85,
    status: 'online' as const,
    tags: ['캐주얼 게임', '주말 플레이어', '소셜'],
  },
  {
    id: 8,
    userId: 'user-8',
    nickname: '날뛰는기린',
    matchRate: 85,
    status: 'online' as const,
    tags: ['캐주얼 게임', '주말 플레이어', '소셜'],
  },
  {
    id: 9,
    userId: 'user-9',
    nickname: '춤추는강아지',
    matchRate: 94,
    status: 'online' as const,
    tags: ['FPS 마스터', '새벽 플레이어', '협력 지향'],
  },
  {
    id: 10,
    userId: 'user-10',
    nickname: '기분좋은곰',
    matchRate: 94,
    status: 'online' as const,
    tags: ['FPS 마스터', '새벽 플레이어', '협력 지향'],
  },
  {
    id: 11,
    userId: 'user-11',
    nickname: '상쾌한고양이',
    matchRate: 94,
    status: 'online' as const,
    tags: ['FPS 마스터', '새벽 플레이어', '협력 지향'],
  },
  {
    id: 12,
    userId: 'user-12',
    nickname: '친절한사자',
    matchRate: 88,
    status: 'online' as const,
    tags: ['RPG 마니아', '저녁 플레이어', '전략적'],
  },
];

export type MatchData = (typeof matchData)[number];
