import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { NextThemesProvider } from '../commons/providers/next-themes/next-themes.provider';
import { ModalProvider } from '../commons/providers/modal/modal.provider';
import { Layout } from '../commons/layout';

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  weight: '100 900',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable}  antialiased`}>
        <NextThemesProvider>
          <ModalProvider>
            <Layout>{children}</Layout>
          </ModalProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
